name: test_tyba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  path: ^1.8.1
  reactive_forms: ^10.0.0
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1

flutter:
  uses-material-design: true
